# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9ZsWBLeEOL1lAS_BX4FezZaOkia1Sy0
"""

import numpy as np
#creating the array
arr=np.array([1,2,3,4,5])
print(arr)

zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

#range of array
arange_arr=np.arange(10)
print(arange_arr)

#reshaping of  array
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

sliced_arr=arr[2:4]
print(sliced_arr)

import numpy as np
#use of vstack
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack(a+b)
print(c)

import numpy as np
#splitting of array
a=np.array(["a","b","c","d"])
a=np.split(a,2)
print(a)

import numpy as np
#transposing of array
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)

import numpy as np
#linear algebra
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#using 'dot' operater
c=np.dot(a,b)
print(c)
#printing eigan value and vetor
d=np.linalg.eig(c)
print(d)
#sum of array
s=np.sum(a,axis=1)
print(s)
s2=np.sum(a,axis=0)
print(s2)

import numpy as np
#statistical operation
a=np.array([1,2,3,4,5])
mean=np.mean(a)
md=np.median(a)
vari=np.var(a)
SD=np.std(a)
print(mean)
print(md)
print(SD)
print(vari)

import numpy as np
data=np.loadtxt("/lova.txt",dtype=int)
d=np.savetxt("/ove.txt",data)
print(data)
print(d)

import numpy as np
#mathplot lib library
import matplotlib.pyplot as plt
a=np.array([1,2])
plt.plot(a)

import numpy as np
#use of stack
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack(a+b)
print(c)



import numpy as  np

m1=np.array([[1,2,3],[2,3,4]])
m2=np.array([[3,7,4],[2,5,1]])
#adding of two  arrays
result=m1+m2
print(result)
#adding of 3 to each element of array1
results=m1+3
print(results)

import numpy as np
#mathplot lib library
import matplotlib.pyplot as plt
a=np.array([1,0,2,8,3,7,4,6,5,9])
plt.plot(a)

#IMPORTING PANDA
import panda as pd