# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-FJqttYtqVq8cOExMAt3vFJsGFH9uTo
"""

#importing pandas
import pandas as pd


a=["kiran","lovaraju","sai","sairam","dimpu","farhan","kalyan","bhushan"]
r=pd.Series(a,index=[39,37,16,31,56,36,22,23])
print(r)

#importing csv file
 import pandas as pd
data=pd.read_csv("/content/mnist_train.csv")
print(data)

#text file importing
import pandas as pd
data=pd.read_csv("/content/lova.txt",sep=" ")
print(data)

#importing excel file
import pandas as pd
data=pd.read_excel("/content/salesworkload.xlsx",sheet_name=0)
print(data)
#printing one row as series
print(data.loc[1])

#printing one row as series
print(data.loc[1])

#calulating mean to data
import pandas as pd
data=pd.read_csv("/content/tableConvert.com_gyhh6h.csv")
print(data)
mv=data["sum"].mean()
df=data.fillna(mv)
print(df)
#using head command
data.head(5)
#using tail command
data.tail(5)
mv=df.drop_duplicates()
print(mv)
data.shape

#using head command
data.head(5)

#using tail command
data.tail(5)

#using duplicate command
mv=df.drop_duplicates()
print(mv)

from google.colab import drive
drive.mount('/content/drive')

#using shape command
data.shape

#concatination
data=pd.read_csv("/content/tableConvert.com_gyhh6h.csv")
data.shape
data_manual=data.tail(10)
data_testing=data.tail(5)
for i in range(1,0,-1):
  data.drop([i],axis=0,inplace=True)
data_manual=pd.concat([data],axis=0)
data_manual.to_csv("last_10_lines_csv")



print(data.groupby(['sum'])['Average'].count())

#printing spevcific column and row
print(data_manual.groupby(['sum'])['Average'].count())

print(data)

#ploting graph using "matplotlib.pyplot" library
import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='green')
plt.title('India vs Australia score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#generating array of 200 values between -pi &+pi
tiger=np.linspace(-2*np.pi,2*np.pi,100)
print(tiger)

plt.plot(tiger,np.sin(tiger),color='red')#sin
#plt.plot(x,y,,color,lable......)
plt.title("sin(x)")
#display plot
plt.show

import numpy as np
import matplotlib.pyplot as plt
#creating x
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
#creating y
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
#plotting
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color='blue',label='India')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color='red',label='Australia')
#combining two graphs
plt.legend(loc='best')
#displaying final graph
plt.show()

import numpy as np
import matplotlib.pyplot as plt

a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]

profit_a=[(a[i]-a[i-1])for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1])for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='company A',marker='>',ms='15',mec='k')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='company B',marker='H')
plt.legend(loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#explode
a=np.array([25,60,5,10])
labe=["AIML","JAVA","PANDAS","NUMPY"]
c=["green","yellow","gray","blue"]
#explo=[0.2,0.1,0.1,0.1]
plt.pie(a,labels=labe,startangle=180,colors=c,textprops={'fontsize':17})
plt.legend(loc="best")
plt.show()

import pandas as pd
df = pd.read_csv('/content/city_temperature.csv')
print(df)
average_temperature=df['AvgTemperature'].mean()
highest_temperature=df['AvgTemperature'].max()
lowest_temperature=df['AvgTemperature'].min()
threshold = 30
days_above_threshold=df[df['AvgTemperature']>threshold].shape[0]
print("Average temperature for the month:",average_temperature)
print("Highest temperature recorded:",highest_temperature)
print("Lowest temperature recorded:",lowest_temperature)
print("Number of days where temperature exceeded",threshold,"degrees Celsius:",days_above_threshold)

#Task1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Load the dataset containing daily temperatures
# Assuming the dataset is in a CSV file named 'temperature_data.csv' with a column named 'temperature'
df = pd.read_csv('/content/city_temperature.csv')
print(df)


average_temperature = df['AvgTemperature'].mean()
highest_temperature = df['AvgTemperature'].max()
lowest_temperature = df['AvgTemperature'].min()
threshold = 30
days_above_threshold = df[df['AvgTemperature'] > threshold].shape[0]


print("Average temperature for the month:", average_temperature)
print("Highest temperature recorded:", highest_temperature)
print("Lowest temperature recorded:", lowest_temperature)
print("Number of days where temperature exceeded", threshold, "degrees Celsius:", days_above_threshold)
#df.plot(kind='line',color='blue')
#plt.title("Temperature for 50 days")
#plt.xlabel("Days")
#plt.ylabel("Temperature")
#plt.show()

plt.plot(df['Day'], df['AvgTemperature'])
plt.xlabel('Day')
plt.ylabel('Temperature (°C)')
plt.title('Daily Temperatures')
plt.show()